"""
Offline demo dataset.

app/data/demo_snapshot.json is generated by scripts/build_demo_snapshot.py
from the INSERT statements in setup/03_load_synthetic_data.sql and
setup/04_cortex_search.sql, so demo mode shows exactly the rows a freshly
provisioned Snowflake account contains.

Each browser session gets its own copy: triage decisions and SAR filings
made in demo mode change only that visitor's copy, never anyone else's.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import streamlit as st

SNAPSHOT_PATH = Path(__file__).resolve().parent.parent / "data" / "demo_snapshot.json"
TABLES = (
    "CUSTOMERS",
    "ACCOUNTS",
    "TRANSACTIONS",
    "AML_ALERTS",
    "ML_RISK_FEATURES",
    "REGULATORY_DOCS_CHUNKS",
)
_STATE_KEY = "_sr_demo_tables"


@st.cache_resource(show_spinner=False)
def _base_tables() -> dict[str, pd.DataFrame]:
    raw = json.loads(SNAPSHOT_PATH.read_text(encoding="utf-8"))
    tables = {name: pd.DataFrame(raw.get(name, [])) for name in TABLES}

    alerts = tables["AML_ALERTS"]
    for col, default in (("ANALYST_ASSIGNED", None), ("SAR_REFERENCE", None), ("UPDATED_AT", None)):
        if col not in alerts.columns:
            alerts[col] = default
    alerts["ANALYST_ASSIGNED"] = alerts["ANALYST_ASSIGNED"].astype(object)
    alerts["INVESTIGATION_NOTES"] = alerts["INVESTIGATION_NOTES"].astype(object)
    alerts["SAR_REFERENCE"] = alerts["SAR_REFERENCE"].astype(object)
    alerts["UPDATED_AT"] = alerts["UPDATED_AT"].astype(object)
    alerts["SAR_FILED"] = alerts["SAR_FILED"].fillna(False).astype(bool)
    return tables


def tables() -> dict[str, pd.DataFrame]:
    """This browser session's mutable copy of the demo tables."""
    if _STATE_KEY not in st.session_state:
        st.session_state[_STATE_KEY] = {name: df.copy(deep=True) for name, df in _base_tables().items()}
    return st.session_state[_STATE_KEY]


def table(name: str) -> pd.DataFrame:
    return tables()[name].copy()


def update_alert(alert_id: str, **changes) -> bool:
    alerts = tables()["AML_ALERTS"]
    mask = alerts["ALERT_ID"] == alert_id
    if not mask.any():
        return False
    for col, value in changes.items():
        if col not in alerts.columns:
            alerts[col] = None
            alerts[col] = alerts[col].astype(object)
        idx = alerts.index[mask]
        for i in idx:
            alerts.at[i, col] = value
    return True


def reset() -> None:
    st.session_state.pop(_STATE_KEY, None)
