"""
SAR Builder — formats investigation data into a structured
Suspicious Activity Report (SAR / STR) document.
"""

from datetime import datetime
from typing import Any


# ── Helpers ───────────────────────────────────────────────────

def _risk_label(score: float) -> str:
    if score >= 0.85:
        return "CRITICAL"
    if score >= 0.70:
        return "HIGH"
    if score >= 0.50:
        return "MEDIUM"
    return "LOW"


def _format_inr(amount: Any) -> str:
    try:
        return f"₹{int(amount):,}"
    except (TypeError, ValueError):
        return str(amount)


def _pep_text(flag: Any) -> str:
    return "Yes — Enhanced Due Diligence required" if flag else "No"


def _sanctions_text(flag: Any) -> str:
    return "⚠️ YES — SANCTIONS MATCH" if flag else "No"


# ── Markdown SAR ──────────────────────────────────────────────

def build_sar_markdown(data: dict) -> str:
    alert    = data.get("alert", {})
    customer = data.get("customer", {})
    txns     = data.get("transactions", [])

    txn_table_rows = "\n".join(
        f"| {t.get('TRANSACTION_ID','—')} | {t.get('TRANSACTION_DATE','—')} "
        f"| {_format_inr(t.get('AMOUNT_INR','—'))} | {t.get('TRANSACTION_TYPE','—')} "
        f"| {t.get('CHANNEL','—')} | {t.get('NARRATION','—')} |"
        for t in txns[:15]
    )

    return f"""# SUSPICIOUS ACTIVITY REPORT (SAR / STR)

---

**SAR Reference:** `{data.get('sar_ref', '—')}`  
**Filing Date:** {data.get('filing_date', datetime.today().strftime('%Y-%m-%d'))}  
**Status:** DRAFT — Pending Submission to {data.get('regulator', 'FIU-IND (RBI)')}

---

## Section 1: Reporting Entity Information

| Field | Value |
|---|---|
| Reporting Institution | {data.get('institution', '—')} |
| Branch / Unit | {data.get('branch', '—')} |
| Reporting Officer | {data.get('reporting_officer', '—')} |
| Recipient Regulator | {data.get('regulator', 'FIU-IND (RBI)')} |
| Report Generated | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} |

---

## Section 2: Subject Information

| Field | Value |
|---|---|
| Customer ID | {customer.get('CUSTOMER_ID', '—')} |
| Full Name / Entity | {customer.get('FULL_NAME', '—')} |
| Entity Type | {customer.get('ENTITY_TYPE', '—')} |
| Country of Origin | {customer.get('COUNTRY_OF_ORIGIN', '—')} |
| KYC Risk Tier | **{customer.get('KYC_TIER', '—')}** |
| Politically Exposed Person (PEP) | {_pep_text(customer.get('PEP_FLAG', False))} |
| Sanctions Flag | {_sanctions_text(customer.get('SANCTIONS_FLAG', False))} |
| Occupation | {customer.get('OCCUPATION', '—')} |
| Last KYC Refresh | {customer.get('LAST_KYC_REFRESH', '—')} |
| Account Open Date | {customer.get('ACCOUNT_OPEN_DATE', '—')} |

---

## Section 3: Suspicious Activity Description

| Field | Value |
|---|---|
| Alert ID | `{alert.get('ALERT_ID', '—')}` |
| Alert Type / Typology | **{alert.get('ALERT_TYPE', '—')}** |
| Severity | **{alert.get('ALERT_SEVERITY', '—')}** |
| Detection Date | {alert.get('ALERT_DATE', '—')} |
| Total Amount Involved | **{_format_inr(alert.get('TOTAL_AMOUNT_INR', 0))}** |
| Trigger Rule | {alert.get('TRIGGER_RULE', '—')} |

### Summary of Suspicious Activity

{data.get('investigation_notes') or '*No investigation notes provided. Please add findings from the Investigation Chat.*'}

---

## Section 4: Transaction Evidence

| Transaction ID | Date & Time | Amount | Type | Channel | Narration |
|---|---|---|---|---|---|
{txn_table_rows if txn_table_rows else '| — | No transactions retrieved | — | — | — | — |'}

---

## Section 5: Regulatory Basis

This SAR is filed in compliance with:

- **RBI Master Direction on KYC, 2016 (Updated 2023) — Para 15:** Banks shall file an STR with FIU-IND within **7 working days** of concluding a transaction is suspicious.
- **Prevention of Money Laundering Act (PMLA), 2002:** Reporting entities are obligated to report suspicious transactions regardless of the amount.
- **FATF Recommendation 20:** Requires prompt reporting of suspicions to the Financial Intelligence Unit.

> ⚠️ **Tipping-off prohibited:** Per RBI Para 15.5, the subject customer must NOT be informed of this SAR filing.

---

## Section 6: Recommended Action

| Action | Priority |
|---|---|
| File STR with FIU-IND within 7 days | 🔴 Mandatory |
| Freeze account pending investigation | ⚠️ Recommended |
| Escalate to Senior Compliance Officer | ⚠️ Recommended |
| Initiate Enhanced Due Diligence (EDD) | 📋 Required for HIGH/CRITICAL |
| Co-ordinate with Law Enforcement if terrorism-linked | 🔴 If applicable |

---

*This document was generated by SentinelReg — AML Risk Intelligence Copilot.*  
*Reference: {data.get('sar_ref', '—')} | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""


# ── Plain text SAR (for submission systems) ───────────────────

def build_sar_text(data: dict) -> str:
    """Returns a plain text version suitable for submission portals."""
    md = build_sar_markdown(data)
    # Strip markdown formatting for plain text output
    import re
    text = re.sub(r"[*#`|]", "", md)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()
