-- ============================================================
-- SentinelReg: Step 1 — Database, Schema, Warehouse & Roles
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- Create dedicated role for SentinelReg
CREATE OR REPLACE ROLE SENTINEL_REG_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE SENTINEL_REG_ROLE;

SET my_user = CURRENT_USER();
GRANT ROLE SENTINEL_REG_ROLE TO USER IDENTIFIER($my_user);

-- Core database and schema
CREATE OR REPLACE DATABASE SENTINEL_REG;
CREATE OR REPLACE SCHEMA SENTINEL_REG.DATA;

GRANT USAGE ON DATABASE SENTINEL_REG TO ROLE SENTINEL_REG_ROLE;
GRANT USAGE ON SCHEMA SENTINEL_REG.DATA TO ROLE SENTINEL_REG_ROLE;
GRANT CREATE AGENT ON SCHEMA SENTINEL_REG.DATA TO ROLE SENTINEL_REG_ROLE;
GRANT CREATE STAGE ON SCHEMA SENTINEL_REG.DATA TO ROLE SENTINEL_REG_ROLE;
GRANT CREATE TABLE ON SCHEMA SENTINEL_REG.DATA TO ROLE SENTINEL_REG_ROLE;
GRANT CREATE VIEW ON SCHEMA SENTINEL_REG.DATA TO ROLE SENTINEL_REG_ROLE;

-- Agent hosting schema (Snowflake Intelligence)
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS;

GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE SENTINEL_REG_ROLE;
GRANT USAGE ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE SENTINEL_REG_ROLE;
GRANT CREATE SNOWFLAKE INTELLIGENCE ON ACCOUNT TO ROLE SENTINEL_REG_ROLE;
GRANT MODIFY ON SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT TO ROLE SENTINEL_REG_ROLE;
GRANT USAGE ON SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT TO ROLE SENTINEL_REG_ROLE;

-- Warehouse — small, cost-efficient
CREATE OR REPLACE WAREHOUSE SENTINEL_REG_WH
WITH
    WAREHOUSE_SIZE    = 'SMALL'
    AUTO_SUSPEND      = 300
    AUTO_RESUME       = TRUE
    INITIALLY_SUSPENDED = FALSE
    COMMENT = 'SentinelReg AML copilot warehouse — auto-suspends after 5 min idle';

GRANT USAGE, OPERATE ON WAREHOUSE SENTINEL_REG_WH TO ROLE SENTINEL_REG_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SENTINEL_REG.DATA TO ROLE SENTINEL_REG_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SENTINEL_REG.DATA TO ROLE SENTINEL_REG_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SENTINEL_REG.DATA TO ROLE SENTINEL_REG_ROLE;

ALTER USER IDENTIFIER($my_user) SET DEFAULT_ROLE = SENTINEL_REG_ROLE;
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'AWS_US';

-- Internal stage to hold semantic model YAML and regulatory docs
USE ROLE SENTINEL_REG_ROLE;
USE DATABASE SENTINEL_REG;
USE SCHEMA DATA;
USE WAREHOUSE SENTINEL_REG_WH;

CREATE OR REPLACE STAGE MODELS
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Holds Cortex Analyst semantic model YAML files';

CREATE OR REPLACE STAGE REGULATORY_DOCS
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Holds regulatory compliance documents for Cortex Search';

GRANT READ ON STAGE MODELS TO ROLE SENTINEL_REG_ROLE;
GRANT READ ON STAGE REGULATORY_DOCS TO ROLE SENTINEL_REG_ROLE;

SELECT 'Step 1 complete: Database, schema, warehouse and roles created.' AS STATUS;
